### ISSUE TITLE
[BUG] Calendar week view on IOS only shows a few days

### ISSUE THREAD

**Issue by SebiWrn** [TUM-Dev/campus_flutter#240] opened 2024-04-04 16:29 UTC
**Calendar week view on IOS only shows a few days**

On IOS if I open the app and select the calendar view, I can only see 4 days, but it should show a whole week like the old campus app did.

**To Reproduce**
1. Go to Calendar
2. Click on Week
3. See error

**Expected behavior**
Week view should show a whole week.

**Smartphone (please complete the following information):**
* Phone: IPhone 12
* OS version: IOS 17.4.1
* Language: DE

**Comment by jakobkoerber** [comment] 2024-04-04 16:38
Thanks for contributing! This is a duplicate of [#235](https://github.com/TUM-Dev/campus_flutter/issues/235), therefore I will close this issue

**Closed** 2024-04-04 16:38 UTC
